services:
  postgresql:
    image: bitnami/postgresql:17.5.0
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_PASSWORD: chatwoot-admin
    volumes:
      - postgresql_data:/bitnami/postgresql
  valkey:
    image: bitnami/valkey:8.1.3
    ports:
      - "6379:6379"
    environment:
      VALKEY_PASSWORD: chatwoot-admin
    volumes:
      - valkey_data:/bitnami/valkey/data

volumes:
  postgresql_data:
  valkey_data:
